url: http://arrc.in
baseurl: ""

# Site settings
title: arrC
email: naveen@arrc.in
description: "Naveen Kumar (arrC or arrcoder) is freelance web and mobile developer/designer who codes in ruby, elixir, python, javascript, swift."
project_status: "21 sep, 2016"

social:
  - title: twitter
    url: http://twitter.com/arrcoder
  - title: github
    url: http://github.com/arrc
  - title: linkedin
    url: https://www.linkedin.com/in/arrcoder

# Build settings
markdown: kramdown
# permalink: pretty
