url: http://arrc.in
baseurl: ""

# Site settings
title: arrC
email: naveen@arrc.in
description: "Naveen Kumar (arrC or arrcoder) is freelance web and mobile developer/designer who codes in ruby, elixir, python, javascript, swift."
project_status: "25th Oct, 2016"
google_analytics: UA-84269502-1

social:
  twitter: http://twitter.com/arrcoder
  github: http://github.com/arrc
  linkedin: https://www.linkedin.com/in/arrcoder

# Build settings
markdown: kramdown
# permalink: pretty
